// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vision_backend.Infrastructure.Data;

#nullable disable

namespace vision_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322131643_AddBalanceTransactionsForVoucherStatements")]
    partial class AddBalanceTransactionsForVoucherStatements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vision_backend.Domain.Entities.AdminRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Name", "CreatedBy")
                        .IsUnique();

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.BalanceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntryDate");

                    b.ToTable("BalanceTransactions");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdminApprovedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentApprovalLevel")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("LeaveTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("LeaveTypeName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OwningSuperAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PillerApprovedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuperAdminApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetPillerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminApprovedById");

                    b.HasIndex("OwningSuperAdminId");

                    b.HasIndex("PillerApprovedById");

                    b.HasIndex("RejectedById");

                    b.HasIndex("SuperAdminApprovedById");

                    b.HasIndex("TargetPillerId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AadharCardNo")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("AdminRoleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankBranch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<Guid?>("DesignationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmergencyContactNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("EsicNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IfscCode")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PanCardNo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PfNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SuperAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminRoleId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("MobileNumber");

                    b.HasIndex("SuperAdminId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AdminApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("AdminApprovedById")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentApprovalLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("OwningSuperAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PillerApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("PillerApprovedById")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ReceiptUrls")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SuperAdminApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SuperAdminApprovedById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TargetPillerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AdminApprovedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("OwningSuperAdminId");

                    b.HasIndex("PillerApprovedById");

                    b.HasIndex("RejectedById");

                    b.HasIndex("SuperAdminApprovedById");

                    b.HasIndex("TargetPillerId");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.VoucherCategoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VoucherCategories");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.AdminRole", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.BalanceTransaction", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.User", "User")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.LeaveRequest", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.User", "AdminApprovedBy")
                        .WithMany()
                        .HasForeignKey("AdminApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "OwningSuperAdmin")
                        .WithMany()
                        .HasForeignKey("OwningSuperAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "PillerApprovedBy")
                        .WithMany()
                        .HasForeignKey("PillerApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "SuperAdminApprovedBy")
                        .WithMany()
                        .HasForeignKey("SuperAdminApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "TargetPiller")
                        .WithMany()
                        .HasForeignKey("TargetPillerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminApprovedBy");

                    b.Navigation("OwningSuperAdmin");

                    b.Navigation("PillerApprovedBy");

                    b.Navigation("RejectedBy");

                    b.Navigation("SuperAdminApprovedBy");

                    b.Navigation("TargetPiller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vision_backend.Domain.Entities.AdminRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.User", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.AdminRole", "AdminRole")
                        .WithMany("Users")
                        .HasForeignKey("AdminRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.Designation", "Designation")
                        .WithMany()
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "SuperAdmin")
                        .WithMany("OwnedPillers")
                        .HasForeignKey("SuperAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminRole");

                    b.Navigation("Designation");

                    b.Navigation("SuperAdmin");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("vision_backend.Domain.Entities.User", "AdminApprovedBy")
                        .WithMany()
                        .HasForeignKey("AdminApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "CreatedBy")
                        .WithMany("Vouchers")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("vision_backend.Domain.Entities.User", "OwningSuperAdmin")
                        .WithMany()
                        .HasForeignKey("OwningSuperAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "PillerApprovedBy")
                        .WithMany()
                        .HasForeignKey("PillerApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "SuperAdminApprovedBy")
                        .WithMany()
                        .HasForeignKey("SuperAdminApprovedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("vision_backend.Domain.Entities.User", "TargetPiller")
                        .WithMany()
                        .HasForeignKey("TargetPillerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminApprovedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("OwningSuperAdmin");

                    b.Navigation("PillerApprovedBy");

                    b.Navigation("RejectedBy");

                    b.Navigation("SuperAdminApprovedBy");

                    b.Navigation("TargetPiller");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.AdminRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("vision_backend.Domain.Entities.User", b =>
                {
                    b.Navigation("BalanceTransactions");

                    b.Navigation("LeaveRequests");

                    b.Navigation("OwnedPillers");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
